version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: discord-bot-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: discord_bot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Discord Bot
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped

    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/discord_bot?authSource=admin
      - GUILD_ID=${GUILD_ID}
      - WELCOME_CHANNEL=${WELCOME_CHANNEL:-welcome}
      - BUG_CHANNEL=${BUG_CHANNEL:-fix-my-bug}
      - RESOURCES_CHANNEL=${RESOURCES_CHANNEL:-resources}
      - RULES_CHANNEL=${RULES_CHANNEL:-rules}
      - LOG_CHANNEL=${LOG_CHANNEL:-bot-logs}
      - MESSAGE_LOG_CHANNEL=${MESSAGE_LOG_CHANNEL:-all-message-logs}
      - MEMBER_COUNT_CHANNEL=${MEMBER_COUNT_CHANNEL:-members}
      - LEVELUP_CHANNEL=${LEVELUP_CHANNEL:-level-ups}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      - ENABLE_DISCORD_LOGGING=${ENABLE_DISCORD_LOGGING:-true}
      - ADMIN_CATEGORY=${ADMIN_CATEGORY:-Admin}
      - GENERAL_CATEGORY=${GENERAL_CATEGORY:-General}
      - LEVEL_CATEGORY=${LEVEL_CATEGORY:-Level}
      - XP_PER_MESSAGE=${XP_PER_MESSAGE:-15}
      - XP_BONUS_MIN=${XP_BONUS_MIN:-5}
      - XP_BONUS_MAX=${XP_BONUS_MAX:-25}
      - XP_COOLDOWN=${XP_COOLDOWN:-60}
      - LEVEL_UP_BASE=${LEVEL_UP_BASE:-100}
      - LEVEL_UP_MULTIPLIER=${LEVEL_UP_MULTIPLIER:-1.5}
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: discord-bot-mongo-express
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin123}
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - bot-network

volumes:
  mongodb_data:
    driver: local

networks:
  bot-network:
    driver: bridge
